In [1]:
#loading data from sklearn datasets
from sklearn.datasets import load_wine

#import librarirs
from sklearn.svm import SVC
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import numpy as np


In [2]:
wine_data = load_wine()


In [3]:
wine_data['data'].shape

(178, 13)

In [4]:
features = wine_data['data']
labels = wine_data['target']

In [5]:
features,labels

(array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [6]:
print(wine_data['DESCR'])

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [7]:
x_train, x_test, y_train, y_test = train_test_split(features, labels)

In [8]:
mm = MinMaxScaler()

X_train_mm = mm.fit_transform(x_train)
X_test_mm = mm.fit_transform(x_test)

In [14]:
svc = SVC(probability=True)
svc.fit(X_train_mm, y_train)

SVC(probability=True)

In [15]:
pred = svc.predict(X_test_mm)
pred

array([0, 0, 0, 2, 2, 0, 1, 1, 2, 2, 1, 1, 0, 0, 0, 1, 2, 1, 0, 1, 1, 1,
       2, 1, 1, 2, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 2, 0, 2, 0, 0, 2,
       1])

In [16]:
print(classification_report(pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        10

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [17]:
svc.class_weight_

array([1., 1., 1.])

In [18]:
pred = svc.predict_proba(X_test_mm)

In [19]:
# np.argmax(pred, axis=1)

In [20]:
lis = [arg.tolist().index(max(arg)) for arg in pred]

In [21]:
print(lis)

[0, 0, 0, 2, 2, 0, 1, 1, 2, 2, 1, 1, 0, 0, 0, 1, 2, 1, 0, 1, 1, 1, 2, 1, 1, 2, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 2, 0, 2, 0, 0, 2, 1]


In [22]:
np.argmax(pred, axis=1)

array([0, 0, 0, 2, 2, 0, 1, 1, 2, 2, 1, 1, 0, 0, 0, 1, 2, 1, 0, 1, 1, 1,
       2, 1, 1, 2, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 2, 0, 2, 0, 0, 2,
       1], dtype=int64)